from __future__ import annotations

import shutil
from pathlib import Path
from typing import Dict, Optional

import pandas as pd

from process_model.clustering import main as run_clustering
from process_model.graphing import main as run_graphing
from process_model.transition_edges import main as run_transition_edges
from process_model.zscore_calculation import main as run_zscore


def _project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _output_root() -> Path:
    return _project_root() / "data" / "outputs"


def _latest_png(dataset_dir: Path) -> Optional[Path]:
    if not dataset_dir.exists():
        return None

    pngs = [path for path in dataset_dir.rglob("*.png") if path.is_file()]
    if not pngs:
        return None

    return sorted(pngs, key=lambda path: path.stat().st_mtime, reverse=True)[0]


def _copy_graphs(graphs: Dict[str, Path], output_dir: Path) -> Dict[str, str]:
    output_dir.mkdir(parents=True, exist_ok=True)

    copied: Dict[str, str] = {}
    for graph_name, source in graphs.items():
        destination = output_dir / f"{graph_name}{source.suffix}"
        shutil.copy2(source, destination)
        copied[graph_name] = str(destination)

    return copied


def _load_cluster_summary(dataset: str) -> Dict[str, object]:
    cluster_csv = _output_root() / dataset / f"behavior_clusters_{dataset}.csv"
    if not cluster_csv.exists():
        return {
            "available": False,
            "teams": 0,
            "clusters": 0,
            "silhouette": None,
        }

    df = pd.read_csv(cluster_csv)
    if df.empty:
        return {
            "available": True,
            "teams": 0,
            "clusters": 0,
            "silhouette": None,
        }

    silhouette = None
    if "silhouette" in df.columns and not df["silhouette"].dropna().empty:
        silhouette = float(df["silhouette"].dropna().iloc[0])

    teams = int(df["team_number"].nunique()) if "team_number" in df.columns else 0
    clusters = int(df["cluster_id"].nunique()) if "cluster_id" in df.columns else 0

    return {
        "available": True,
        "teams": teams,
        "clusters": clusters,
        "silhouette": silhouette,
    }


def generate_graphs(csv_path: str, output_dir: str) -> Dict[str, str]:
    """
    Run the full process-model pipeline and return graph PNG paths.

    Parameters
    ----------
    csv_path: str
        Included for API compatibility with callers; current pipeline uses
        project-level files generated by upstream scripts.
    output_dir: str
        Directory where selected graph PNGs are copied.

    Returns
    -------
    Dict[str, str]
        Mapping of graph name to copied png path.
    """
    _ = csv_path

    run_transition_edges()
    run_zscore()
    run_clustering()
    run_graphing()

    root = _output_root()
    selected_graphs: Dict[str, Path] = {}

    pr_graph = _latest_png(root / "pr")
    if pr_graph is not None:
        selected_graphs["pr_graph"] = pr_graph

    branching_graph = _latest_png(root / "branching")
    if branching_graph is not None:
        selected_graphs["branching_graph"] = branching_graph

    communication_graph = _latest_png(root / "communication")
    if communication_graph is not None:
        selected_graphs["communication_graph"] = communication_graph

    if not selected_graphs:
        return {}

    return _copy_graphs(selected_graphs, Path(output_dir))


def get_process_stats(csv_path: str) -> Dict[str, object]:
    """
    Return process-model summary statistics for downstream report embedding.

    Parameters
    ----------
    csv_path: str
        Included for API compatibility with callers; current stats are computed
        from standard output artifacts.

    Returns
    -------
    Dict[str, object]
        Aggregated stats per dataset and total graph count.
    """
    _ = csv_path

    output_root = _output_root()
    all_pngs = [path for path in output_root.rglob("*.png") if path.is_file()]

    datasets = {
        "pr": _load_cluster_summary("pr"),
        "branching": _load_cluster_summary("branching"),
        "communication": _load_cluster_summary("communication"),
    }
    available_datasets = sum(1 for value in datasets.values() if value["available"])

    return {
        "total_graph_files": len(all_pngs),
        "available_datasets": available_datasets,
        "datasets": datasets,
    }
